name: slack notif composite

inputs:
  job_build_status:
    description: "Status of 'actual' job (set in 'needs:') since job.status is status of current one"
    required: true
  trigger_condition:
    description: "'always' by default otherwise could be 'failure', 'cancelled'"
    required: false
    default: 'always'
  SLACK_WEBHOOK_URL:
    description: 'slack webhook url secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: slack notification
      uses: https://github.com/slackapi/slack-github-action@v1.24.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "username": "giteaActions", 
            "icon_emoji": ":gitea:",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Build on repository <${{ gitea.event.repository.html_url }}|${{ gitea.event.repository.full_name }}> status: *${{ inputs.job_build_status }}*"
                }
              }
            ],
            "attachments": [
              {
                  "color": "${{ inputs.job_build_status == 'success' && '#22bb33' || inputs.job_build_status == 'failure' && '#bb2124' || '#f0ad4e' }}",
                  "blocks": [
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "*Branch*\n${{ gitea.ref_name }}"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "*Actions URL*\n<${{ gitea.event.repository.html_url }}/actions/runs/${{ gitea.run_number }}|job URL>"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "*Commit*\n<${{ gitea.event.head_commit.url }}|${{ gitea.event.head_commit.id }}>"
                          }
                      },
                      {
                          "type": "section",
                          "text": {
                              "type": "mrkdwn",
                              "text": "*Author*\n${{ gitea.event.head_commit.committer.username }}"
                          }
                      }
                  ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK