name: Run Actions
run-name: ${{ github.actor }} run test

on: workflow_dispatch

jobs:
  ubuntu-output:
    runs-on: ubuntu-latest
    steps:
      - name: Event information
        env:
            EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT
        shell: bash
      - name: OS information
        run: |
          echo ${{ runner.os }}
          volontary-crashing
        shell: bash
  send-notif:
    if: always()
    needs: ubuntu-output
    uses: ./.github/workflows/_send_notif.yaml
    with:
      job_build_status: ${{ needs.ubuntu-output.result }}
    secrets: inherit
